#%RAML 1.0
title: MoonGUI
version: v1
baseUri: /rest
protocols:
  - HTTP
description: |
  This API enables the Contact between
  the Backend Server and The Frontend
  GUI
mediaType:
  - application/json
/:
  head:
    responses:
      200:
        description: Indicates that the Connection to the Resources is correct set
  /system/:
    description: For System Relevant Tasks
    get:
      protocols:
        - HTTP
      description: Get all System Relevant Information
      responses:
        200:
          body:
            application/json:
              default: {arch:string,cores:number,hostname:string,lua:{status:boolean,version:string},os:string,user:string}
/moongen/:
  description: |
    The Entry Point for the MoonGen Live handling to create or get the execution
  get:
    description: Returns the number of the running System
    responses:
      200:
        description: Returns the Number of the Running System
        body:
          application/json:
            type: {execution:number}
      404:
        description: The System is not longer running or was not started
  post:
    description: Starts MoonGen with the Specified Options
    responses:
      200:
        description: Returns the Number of the Running System
        body:
          application/json:
            type: {execution:number}
  /{execution}/:
    delete:
      description: Stops the running System
      responses:
        200:
          description: The Ressources was successfully stoped
        404:
          description: The System was not longer running
    /log:
      get:
        description: Returns the Log File and the number of read Lines as well as the seek position
        body:
          application/json:
            default: {line:number,seek:number,log:array}
        responses:
          200:
            description: File exists and is returned
            body:
              application/text:
                default: {lines:number,content:file}
          304:
            description: Nothing Changed
          404:
            description: File did not exist
        queryParameters:
          line:
            type: number
            description: The line number from which we should start
          seek:
            type: number
            description: The position in the file for reading
    get:
      description: Returns the current data
      responses:
        200:
          description: All Data correct
        404:
          description: No Execution working
