#%RAML 1.0
title: MoonGen
version: v1
baseUri: localhost:103546/
protocols:
  - HTTP
mediaType:
  - application/JSON
description: |
  This API enables the Contact between
  the Backend Server and MoonGen
